export const FETCH_RANDOM_FACT = 'FETCH_RANDOM_FACT';
export const SET_RANDOM_FACT = 'SET_RANDOM_FACT';

export const FETCH_ALL_CATEGORY = 'FETCH_ALL_CATEGORY';
export const SET_ALL_CATEGORY = 'SET_ALL_CATEGORY';

export const FETCH_FACT_BY_CATEGORY = 'FETCH_FACT_BY_CATEGORY';
export const SET_FACT_BY_CATEGORY = 'SET_FACT_BY_CATEGORY';

export const UPDATE_FAVOURITE_JOKES = 'UPDATE_FAVOURITE_JOKES';